env:
  browser: true
  es2021: true
extends:
  # I want to know the best practices for the settings here.
  # I don't know it, but this so many extends are enough to make it feel non-exemplary.
  - plugin:markdown/recommended
  - plugin:yaml/recommended
  - plugin:editorconfig/noconflict
  - plugin:jsdoc/recommended
  - eslint:recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - airbnb-typescript
  - plugin:prettier/recommended
overrides:
  - files:
      - '*.?(c)[jt]s'
    rules:
      '@typescript-eslint/no-var-requires': 'off'
  - extends:
      - plugin:json/recommended
    files:
      - '*.json'
  - env:
      jest/globals: true
      node: true
    extends:
      - plugin:jest/recommended
    files:
      - '*.spec.?([cm])[jt]s?(x)'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    impliedStrict: true
    jsx: true
  extraFileExtensions:
    - '.cjs'
    - '.cts'
    - '.json'
    - '.mjs'
    - '.mts'
    - '.yml'
  project: ./tsconfig.eslint.json
  sourceType: 'module'
root: true
rules:
  '@typescript-eslint/consistent-type-imports': warn
  '@typescript-eslint/dot-notation': 'off'
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '.storybook/main.js'
        - '**/*.config.?([cm])[jt]s'
        - '**/*.stories.?([cm])[jt]s?(x)'
  import/order: warn
  jsdoc/require-param-type: 'off'
  jsdoc/require-returns-type: 'off'
  react/prop-types: 'off'
  react/react-in-jsx-scope: 'off'
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
  react:
    version: detect
