name: Actions on pushed main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use the Node.js specified version
        uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
