name: Actions on pushed main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use the Node.js specified version
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version-file: .node-version
      - env:
          HUSKY: 0
        name: Install the dependencies
        run: npm ci
      - name: Linting the code
        run: npm run lint
