name: Actions on pushed main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "17"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use the Node.js version ${{ env.NODE_VERSION }} specified in the workflow
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: ${{ env.NODE_VERSION }}
      - name: Install the dependencies
        run: npm ci
